add null_or_empty

diff --git a/.github/workflows/whatever.yml b/.github/workflows/whatever.yml
--- a/.github/workflows/whatever.yml
+++ b/.github/workflows/whatever.yml
@@ -16,7 +16,10 @@ jobs:
         run: npm install
 
       - name: Lint 🧐
-        run: npm run lint; echo 'fail'; exit 1
+        run: npm run lint; 
+        
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
 
       - name: Build 🏗️
         run: npm run build
