add null_or_empty

diff --git a/.github/workflows/whatever.yml b/.github/workflows/whatever.yml
--- a/.github/workflows/whatever.yml
+++ b/.github/workflows/whatever.yml
@@ -8,7 +8,7 @@ jobs:
 
     steps:
       - name: Checkout 🛎️
-         uses: actions/checkout@v2
+        uses: actions/checkout@v2
         with:
           persist-credentials: false
 
@@ -16,7 +16,7 @@ jobs:
         run: npm install
 
       - name: Lint 🧐
-        run: npm run lint
+        run: npm run lint; echo 'fail'; exit 1
 
       - name: Build 🏗️
         run: npm run build
